# Introduction to Numpy
## Numpy is
Description here

In [2]:
#Numpy arrays
import numpy as np

In [3]:
#Create a numpy array
list_1 = [1,2,3,4]
list_1

[1, 2, 3, 4]

In [4]:
np.array(list_1)

array([1, 2, 3, 4])

In [6]:
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3rd parameter is the step/gap

In [10]:
np.arange(1,10, 2) 

array([1, 3, 5, 7, 9])

In [20]:
np.zeros(5) 
#1 dimentional array of five columns. 

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,4)) #ordering numpy of multi-dimentional arrays

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# how to check the size of dimentional arrays: check the number of square brackets in the array. '[[ ]]'means two dimentions

In [13]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace(0, 10, 101) #Return evenly spaced numbers over a specified interval.

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [88]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# Numpy random modules
np.random.rand(3,4)

array([[0.44664072, 0.70365406, 0.19677154, 0.32142621],
       [0.60268003, 0.41838804, 0.13641994, 0.62177159],
       [0.17595533, 0.32112723, 0.28865195, 0.73664608]])

In [26]:
np.random.randn(5)

array([ 0.36268961,  0.41726844, -0.04249447, -1.2421951 , -0.70638542])

In [27]:
np.random.randint(10,20)

18

In [30]:
arr = np.arange(1, 20, 2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [39]:
arr.reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [40]:
arr.max()

19

In [41]:
arr.min()

1

In [42]:
arr.argmax()

9

In [43]:
arr.argmin()

0

### Numpy Operations

In [44]:
arr2 = np.arange(1,10)
arr3 = np.arange(11,20)

In [45]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr3

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
arr2 + arr3

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [48]:
arr2 ** arr3

array([                  1,                4096,             1594323,
                 268435456,         30517578125,       2821109907456,
           232630513987207,   18014398509481984, 1350851717672992089])

In [49]:
arr2 * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

## Numpy Indexing and Selection

In [50]:
example_arr = np.arange(1,21).reshape(4,5)
example_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [51]:
example_arr[2] #indexing 2 means printing raw line 2 (3rd out of 0-3)

array([11, 12, 13, 14, 15])

In [62]:
example_arr[:2] # slicing raw 0:2 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [63]:
example_arr[:2,:2]# slicing raw 0:2 and column 0:2

array([[1, 2],
       [6, 7]])

In [70]:
example_arr[:2,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

## Broadcasting
#### Assigning new values to specific area you wish to change

In [71]:
example_arr[1:4]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [74]:
example_arr[1:4] = 30
example_arr 

array([[ 1,  2,  3,  4,  5],
       [30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30]])

In [76]:
example_arr[3]=[29,20,10,2,4]
example_arr

array([[ 1,  2,  3,  4,  5],
       [30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30],
       [29, 20, 10,  2,  4]])

### Conditional selection

In [81]:
example_arr2 = np.arange(21,41).reshape(4,5)
example_arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [82]:
example_arr2[example_arr2 > 30] 

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [86]:
example_arr2[(example_arr2 > 30) & (example_arr2 < 35)] 

array([31, 32, 33, 34])